name: Build and Deploy to S3

on:
  push:
    branches:
      - quality
      - stage
      - production
jobs:
  get-environment:
    name: Get environment
    outputs:
      my_env: ${{ steps.setenv.outputs.my_env }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout github code
      id: checkout-id
      uses: actions/checkout@v4
    - id: setenv
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/stage" ]]; then
          echo "my_env=stage" >> $GITHUB_OUTPUT
        elif [[ "${{ github.ref }}" == "refs/heads/quality" ]]; then
          echo "my_env=quality" >> $GITHUB_OUTPUT
        elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "my_env=production" >> $GITHUB_OUTPUT
        fi
  build-deploy:
    runs-on: ubuntu-latest
    needs: get-environment
    environment: 
      name: ${{ needs.get-environment.outputs.my_env }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install AWS CLI
      run: |
        python -m pip install --upgrade pip
        pip install awscli
    - name: Checkout github code
      id: checkout-id
      uses: actions/checkout@v4
    - name: test
      run: |
          echo "${{ vars.ENVIRONMENT }}"
          echo "${{ vars.AWS_DEFAULT_REGION }}"
    - name: Install dependencies
      run: |
        cd code
        npm install
    - name: Build and capture output
      # env:
      #   VITE_API_URL: ${{vars.VITE_API_URL}}
      run: |
        cd code
        export VITE_API_URL
        npm run build
    - name: Copy files to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ vars.AWS_DEFAULT_REGION }}
      run: |
        cd code/dist
        ls
        aws s3 sync . s3://${{ vars.ENVIRONMENT }}-luminous-frontend --exclude '.git/*' --exclude '.github/*'
    - name: Install dependencies (for Storybook)
      run: |
        cd code
        npm install
    - name: Build and capture output Storybook
      run: |
        cd code
        npm run build-storybook
    - name: Copy files to S3 (Storybook)
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ vars.AWS_DEFAULT_REGION }}
      run: |
        cd code/storybook-static
        ls
        aws s3 sync . s3://${{ vars.ENVIRONMENT }}-luminous-frontend-storybook --exclude '.git/*' --exclude '.github/*'
